name: temtem_api_wrapper
description: Wrapper for all the methods of the unofficial Temtem REST API.
version: 0.1.1+3
homepage: https://github.com/TesteurManiak
repository: https://github.com/TesteurManiak/temtem_api_wrapper/

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  http: ^0.13.4

dev_dependencies:
  lint: ^1.8.2
  test: ^1.20.2
