name: temtem_api_wrapper
description: Wrapper for all the methods of the unofficial Temtem REST API.
version: 0.2.0
homepage: https://github.com/TesteurManiak
repository: https://github.com/TesteurManiak/temtem_api_wrapper/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6

dev_dependencies:
  http_mock_adapter: ^0.3.3
  lint: ^1.10.0
  test: ^1.21.4
